name: 'Testing'
description: 'Run npm run test for nodejs services'

inputs:
  npm_token:
    description: 'npm_token'
    required: true
  node_v:
    required: false
    description: 'node version to run'
    default: "12.14.1"
  redis_url:
    required: false
    description: 'redis url to run with'
    default: ''
  db_url:
    description: 'db url to run with'
    required: false
    default: ''
  schema_path:
    description: 'schema files path'
    required: false
    default: ''
  github_token_schema:
    description: 'github_token_schema'
    required: false
    default: ''    

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: totango/schema
        ssh-key: ${{ inputs.github_token_schema }}
        ref: refs/heads/master
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: copy-file
      shell: bash
      run: |
        cp -R ./schema ./${{ inputs.schema_path }}
    - name: setup node
      uses: actions/setup-node@master
      with:
        node-version: ${{ inputs.node_v }}
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Run tests
      shell: bash
      env:
        REDIS_URL: ${{ inputs.redis_url }}
        GLOBAL_REDIS_URL: ${{ inputs.redis_url }}
        DB_URL: ${{ inputs.db_url }}
        SCHEMA_PATH: ${{ inputs.schema_path }}
      run: |
        env IS_LOCAL_LOG=true npm run test