name: Node testing with DB and Redis workflow

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node_v:
        type: string
        required: false
        default: "12.14.1"
env:
  ## Sets environment variable
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_OPTIONS: "--max-old-space-size=4096"
  HUSKY: 0

permissions:
  contents: read
  packages: read

jobs:
  configure:
    runs-on: app_backend
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  testing:
    needs: configure
    # The type of runner that the job will run on
    # Containers must run in Linux based operating systems
    runs-on: app_backend

    container:
      image: node:${{ inputs.node_v }}
      options: --user ${{ needs.configure.outputs.uid_gid }}

    # Service containers to add`
    services:
      # Label used to access the service container
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: '1234'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Testing
        uses: totango/shared-github-actions/.github/actions/testing@testing-with-github-token
        id: image
        with:
          node_v: ${{ inputs.node_v }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          db_url: mysql
          redis_url: redis
          github_token: ${{ secrets.GITHUB_TOKEN }}