name: Node linting workflow

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node_v:
        type: string
        required: false
        default: "12.14.1"
env:
  ## Sets environment variable
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ inputs.node_v }}

      # install application dependencies
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: |
          npm install
      - name: eslint check
        run: |
          npx eslint .